apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app.kubernetes.io/name    : django-deploy
    app.kubernetes.io/instance: django-v1
    app.kubernetes.io/version : "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      project: django
  template:
    metadata:
      labels:
        project: django
    spec:
      volumes:
        - name: secret-volume
          secret:
            secretName: ssl-cert
      containers:
        - name: django
          image: magomed993/django_app:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: django-secret
          volumeMounts:
            - name: secret-volume
              mountPath: "/root/.postgresql"
              readOnly: true