apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: ssl-cert
  containers:
    - name: ubuntu
      image: ubuntu:22.04
      args:
        - /bin/sh
        - -c
        - |
          apt-get update &&
          apt-get install -y postgresql-client &&
          sleep 600500
      volumeMounts:
        - name: secret-volume
          mountPath: "/root/.postgresql"
          readOnly: true
      ports:
        - containerPort: 80