apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions-once
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django-clearsession
            image: magomed993/django_app:latest
            command: ["python", "manage.py", "clearsessions"]
            envFrom:
              - secretRef:
                  name: django-secret
          restartPolicy: OnFailure