apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app.kubernetes.io/name    : django-deploy
    app.kubernetes.io/instance: django-v1
    app.kubernetes.io/version : "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      project: django
  template:
    metadata:
      labels:
        project: django
    spec:
      containers:
        - name: django
          image: magomed993/django_app:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: django-secret
---
apiVersion: v1
kind: Service
metadata:
  name: django-svc
  labels:
    app.kubernetes.io/name: django
    app.kubernetes.io/instance: django-svc
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: server
spec:
  selector:
    project: django
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80
      targetPort: 80
  type: NodePort